-- Memory Layer Schema for TomeHub

-- 1. Chat Sessions (Stateful Conversations)
CREATE TABLE TOMEHUB_CHAT_SESSIONS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIREBASE_UID VARCHAR2(255) NOT NULL,
    TITLE VARCHAR2(255) DEFAULT 'New Chat',
    RUNNING_SUMMARY CLOB, -- Compressed history context
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chat_uid ON TOMEHUB_CHAT_SESSIONS(FIREBASE_UID);

-- 2. Chat Messages (Raw History)
CREATE TABLE TOMEHUB_CHAT_MESSAGES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SESSION_ID NUMBER NOT NULL,
    ROLE VARCHAR2(20) CHECK (ROLE IN ('user', 'assistant', 'system')),
    CONTENT CLOB NOT NULL,
    CITATIONS CLOB CHECK (CITATIONS IS JSON), -- JSON array of source refs
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_session FOREIGN KEY (SESSION_ID) REFERENCES TOMEHUB_CHAT_SESSIONS(ID) ON DELETE CASCADE
);

CREATE INDEX idx_msg_session ON TOMEHUB_CHAT_MESSAGES(SESSION_ID);

-- 3. File Reports (Document Intelligence)
CREATE TABLE TOMEHUB_FILE_REPORTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOOK_ID VARCHAR2(255) NOT NULL, -- Logical ID grouping chunks
    FIREBASE_UID VARCHAR2(255) NOT NULL,
    SUMMARY_TEXT CLOB, -- High level TLDR
    KEY_TOPICS CLOB CHECK (KEY_TOPICS IS JSON), -- ["Topic A", "Topic B"]
    ENTITIES CLOB CHECK (ENTITIES IS JSON), -- [{"name": "X", "type": "Person"}]
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_book_report UNIQUE (BOOK_ID, FIREBASE_UID)
);

CREATE INDEX idx_report_book ON TOMEHUB_FILE_REPORTS(BOOK_ID);
