
-- TOMEHUB_CONCEPTS: Stores extracted semantic entities
CREATE TABLE TOMEHUB_CONCEPTS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(255) UNIQUE NOT NULL,
    CONCEPT_TYPE VARCHAR2(50), -- PERSON, PHILOSOPHY, EVENT, etc.
    EMBEDDING VECTOR(1024, FLOAT32) -- For semantic concept lookup
);

-- TOMEHUB_RELATIONS: Stores relationships between concepts (The "Bridges")
CREATE TABLE TOMEHUB_RELATIONS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SRC_ID NUMBER NOT NULL,
    DST_ID NUMBER NOT NULL,
    REL_TYPE VARCHAR2(100), -- "INFLUENCED", "CRITIQUED", "DEFINES", etc.
    WEIGHT NUMBER DEFAULT 1.0, -- Confidence score of the relationship (0.0 - 1.0)
    CONSTRAINT fk_src FOREIGN KEY (SRC_ID) REFERENCES TOMEHUB_CONCEPTS(ID),
    CONSTRAINT fk_dst FOREIGN KEY (DST_ID) REFERENCES TOMEHUB_CONCEPTS(ID)
);

-- TOMEHUB_CONCEPT_CHUNKS: Links concepts back to the source text fragments
CREATE TABLE TOMEHUB_CONCEPT_CHUNKS (
    CONCEPT_ID NUMBER NOT NULL,
    CONTENT_ID NUMBER NOT NULL, -- Links to TOMEHUB_CONTENT(ID)
    STRENGTH NUMBER DEFAULT 1,  -- How relevant the concept is to this chunk
    PRIMARY KEY (CONCEPT_ID, CONTENT_ID),
    CONSTRAINT fk_concept FOREIGN KEY (CONCEPT_ID) REFERENCES TOMEHUB_CONCEPTS(ID)
    -- CONTENT_ID depends on the PK of TOMEHUB_CONTENT (usually rowid or a generated ID)
);

-- CREATE PROPERTY GRAPH (Oracle 23ai Syntax)
-- This creates a logic view on top of the tables for PGQL/Graph queries
CREATE PROPERTY GRAPH TOMEHUB_GRAPH
  VERTEX TABLES (
    TOMEHUB_CONCEPTS
      KEY (ID)
      LABEL CONCEPT
      PROPERTIES (NAME, CONCEPT_TYPE)
  )
  EDGE TABLES (
    TOMEHUB_RELATIONS
      KEY (ID)
      SOURCE KEY (SRC_ID) REFERENCES TOMEHUB_CONCEPTS(ID)
      DESTINATION KEY (DST_ID) REFERENCES TOMEHUB_CONCEPTS(ID)
      LABEL RELATED_TO
      PROPERTIES (REL_TYPE, WEIGHT)
  );

-- INDEXES for fast retrieval
CREATE INDEX idx_concepts_name ON TOMEHUB_CONCEPTS(NAME);
CREATE VECTOR INDEX idx_concepts_vec ON TOMEHUB_CONCEPTS(EMBEDDING) 
ORGANIZATION NEIGHBOR PARTITIONS
DISTANCE COSINE
WITH TARGET ACCURACY 95;
