ALTER TABLE TOMEHUB_INGESTED_FILES ADD (
    STORAGE_BACKEND VARCHAR2(40),
    BUCKET_NAME VARCHAR2(255),
    OBJECT_KEY VARCHAR2(1024),
    SIZE_BYTES NUMBER,
    STORAGE_STATUS VARCHAR2(40),
    PARSE_PATH VARCHAR2(40),
    PARSE_STATUS VARCHAR2(40),
    OCI_JOB_ID VARCHAR2(255),
    OCI_OUTPUT_PREFIX VARCHAR2(1024),
    STORAGE_WARNING VARCHAR2(200),
    CONTENT_TYPE VARCHAR2(40),
    MIME_TYPE VARCHAR2(120),
    SHA256 VARCHAR2(128),
    ERROR_MESSAGE VARCHAR2(1000)
);

CREATE INDEX IDX_INGEST_STORAGE_UID ON TOMEHUB_INGESTED_FILES (FIREBASE_UID, STORAGE_STATUS);
CREATE INDEX IDX_INGEST_PARSE_STATUS ON TOMEHUB_INGESTED_FILES (PARSE_STATUS, UPDATED_AT);
