ALTER TABLE TOMEHUB_INGESTED_FILES ADD (
    CLASSIFICATION_ROUTE VARCHAR2(40),
    PARSE_ENGINE VARCHAR2(40),
    FALLBACK_ENGINE VARCHAR2(40),
    CLASSIFIER_METRICS_JSON CLOB,
    QUALITY_METRICS_JSON CLOB,
    ROUTING_METRICS_JSON CLOB,
    PARSE_TIME_MS NUMBER,
    PAGES NUMBER,
    CHARS_EXTRACTED NUMBER,
    GARBLED_RATIO NUMBER,
    AVG_CHUNK_TOKENS NUMBER,
    FALLBACK_TRIGGERED NUMBER(1),
    SHARD_COUNT NUMBER,
    SHARD_FAILED_COUNT NUMBER
);

CREATE INDEX IDX_INGEST_ROUTE_ENGINE ON TOMEHUB_INGESTED_FILES (CLASSIFICATION_ROUTE, PARSE_ENGINE, UPDATED_AT);
