BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE TOMEHUB_EXTERNAL_API_KEYS (
            ID NUMBER PRIMARY KEY,
            OWNER_FIREBASE_UID VARCHAR2(128 CHAR) NOT NULL,
            KEY_PREFIX VARCHAR2(20 CHAR) NOT NULL,
            KEY_HASH VARCHAR2(64 CHAR) NOT NULL,
            LABEL VARCHAR2(255 CHAR),
            SCOPES_JSON CLOB,
            STATUS VARCHAR2(20 CHAR) DEFAULT ''ACTIVE'' NOT NULL,
            EXPIRES_AT TIMESTAMP NULL,
            LAST_USED_AT TIMESTAMP NULL,
            LAST_IP VARCHAR2(128 CHAR),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            REVOKED_AT TIMESTAMP NULL
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE SEQUENCE TOMEHUB_EXTERNAL_API_KEYS_SEQ
        START WITH 1
        INCREMENT BY 1
        NOCACHE
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE UNIQUE INDEX TOMEHUB_EXT_API_KEYS_PREFIX_UQ
        ON TOMEHUB_EXTERNAL_API_KEYS (KEY_PREFIX)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX TOMEHUB_EXT_API_KEYS_OWNER_IDX
        ON TOMEHUB_EXTERNAL_API_KEYS (OWNER_FIREBASE_UID, STATUS)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE TOMEHUB_EXTERNAL_API_KEYS
        ADD CONSTRAINT TOMEHUB_EXT_API_KEYS_STATUS_CHK
        CHECK (STATUS IN (''ACTIVE'', ''REVOKED''))
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-955, -2261) THEN
            RAISE;
        END IF;
END;
/
