-- Phase 6: Add semantic classification columns to TOMEHUB_CONTENT
-- Run this migration once on your Oracle database

-- Add new columns for ingest-time passage tagging
ALTER TABLE TOMEHUB_CONTENT ADD (
    PASSAGE_TYPE VARCHAR2(20),         -- DEFINITION, THEORY, ANALOGY, SITUATIONAL, SOCIETAL
    QUOTABILITY VARCHAR2(10),          -- HIGH, MEDIUM, LOW
    CLASSIFIER_CONFIDENCE NUMBER(3,2)  -- 0.00 to 1.00
);

-- Create index for efficient filtering by passage type
CREATE INDEX IDX_TOMEHUB_PASSAGE_TYPE ON TOMEHUB_CONTENT(PASSAGE_TYPE);
CREATE INDEX IDX_TOMEHUB_QUOTABILITY ON TOMEHUB_CONTENT(QUOTABILITY);

-- Comment for documentation
COMMENT ON COLUMN TOMEHUB_CONTENT.PASSAGE_TYPE IS 'Semantic type: DEFINITION, THEORY, ANALOGY, SITUATIONAL, SOCIETAL';
COMMENT ON COLUMN TOMEHUB_CONTENT.QUOTABILITY IS 'Quote priority: HIGH (verbatim), MEDIUM (can quote), LOW (synthesize)';
COMMENT ON COLUMN TOMEHUB_CONTENT.CLASSIFIER_CONFIDENCE IS 'Confidence score from semantic classifier (0.0-1.0)';

-- Update existing rows with default values (run once)
UPDATE TOMEHUB_CONTENT 
SET PASSAGE_TYPE = 'SITUATIONAL', 
    QUOTABILITY = 'MEDIUM',
    CLASSIFIER_CONFIDENCE = 0.50
WHERE PASSAGE_TYPE IS NULL;

COMMIT;

-- Verify the migration
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'TOMEHUB_CONTENT' 
AND COLUMN_NAME IN ('PASSAGE_TYPE', 'QUOTABILITY', 'CLASSIFIER_CONFIDENCE');
