-- Phase X: make Flow session tracking UUID-compatible.
-- 1) Drop legacy FK to TOMEHUB_CHAT_SESSIONS (chat ids are numeric, flow ids are UUID).
-- 2) Change TOMEHUB_FLOW_SEEN.SESSION_ID from NUMBER to VARCHAR2(128).

DECLARE
  v_has_fk NUMBER := 0;
  v_data_type VARCHAR2(128);
BEGIN
  SELECT COUNT(*)
    INTO v_has_fk
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'TOMEHUB_FLOW_SEEN'
     AND CONSTRAINT_NAME = 'FK_FLOW_SESSION';

  IF v_has_fk > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TOMEHUB_FLOW_SEEN DROP CONSTRAINT FK_FLOW_SESSION';
  END IF;

  SELECT DATA_TYPE
    INTO v_data_type
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'TOMEHUB_FLOW_SEEN'
     AND COLUMN_NAME = 'SESSION_ID';

  IF v_data_type <> 'VARCHAR2' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TOMEHUB_FLOW_SEEN MODIFY (SESSION_ID VARCHAR2(128))';
  END IF;
END;
/
