-- Phase X: Description Embedding for Concepts (768-dim)

ALTER TABLE TOMEHUB_CONCEPTS
ADD (DESCRIPTION_EMBEDDING VECTOR(768, FLOAT32));

CREATE VECTOR INDEX idx_concepts_desc_vec ON TOMEHUB_CONCEPTS(DESCRIPTION_EMBEDDING)
ORGANIZATION NEIGHBOR PARTITIONS
DISTANCE COSINE
WITH TARGET ACCURACY 95;
