-- Phase X: Concept Aliases (Normalization)

CREATE TABLE TOMEHUB_CONCEPT_ALIASES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONCEPT_ID NUMBER NOT NULL,
    ALIAS VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alias_concept FOREIGN KEY (CONCEPT_ID) REFERENCES TOMEHUB_CONCEPTS(ID)
);

CREATE UNIQUE INDEX uidx_concept_alias_lower ON TOMEHUB_CONCEPT_ALIASES(LOWER(ALIAS));
CREATE INDEX idx_concept_alias_concept_id ON TOMEHUB_CONCEPT_ALIASES(CONCEPT_ID);
