-- Phase X: Ingestion Status Tracking
-- Tracks PDF/EPUB ingestion status and source file name per book/user

CREATE TABLE TOMEHUB_INGESTED_FILES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOOK_ID VARCHAR2(255) NOT NULL,
    FIREBASE_UID VARCHAR2(255) NOT NULL,
    SOURCE_FILE_NAME VARCHAR2(512),
    STATUS VARCHAR2(20),
    CHUNK_COUNT NUMBER,
    EMBEDDING_COUNT NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ingest_book_uid UNIQUE (BOOK_ID, FIREBASE_UID)
);

CREATE INDEX idx_ingest_book_uid ON TOMEHUB_INGESTED_FILES(BOOK_ID, FIREBASE_UID);
